export const FETCH_POSTS="FETCH_POSTS";
export const FETCH_POSTS_SUCCESS="FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE="FETCH_POSTS_FAILURE";

export const CREATE_POST="CREATE_POST";
export const DELETE_POST="DELETE_POST";